blank_issues_enabled: true
contact_links:
  - name: Bitweb Core Security Policy
    url: https://github.com/bitweb-project/bitweb/blob/master/SECURITY.md
    about: View security policy
  - name: Bitweb Core Developers
    url: https://bitwebcore.net
    about: Bitweb Core homepage
